(() => {
'use strict';
let O=[];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function group(v){const x=norm(v);if(x.includes('volunt'))return'Voluntariado';if(/trabalho|vaga|emprego|estagio/.test(x))return'Trabalho';if(/curso|capacit|formacao|mentoria/.test(x))return'Cursos e capacitações';if(/summit|congres|forum|workshop|semin/.test(x))return'Congressos & Summits';return'Outros'}
function days(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v||'')))return null;const t=new Date(new Date().toLocaleString('en-US',{timeZone:'America/Sao_Paulo'}));t.setHours(0,0,0,0);const[y,m,d]=v.split('-').map(Number);return Math.round((new Date(y,m-1,d)-t)/86400000)}
function status(o){const d=days(o.PrazoInscricao);if(d!==null){if(d<0)return'Encerrada';if(d<=7)return'Encerra em breve'}return o.Status||'Inscrições abertas'}
function dateBR(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(v||'')))return'';const[y,m,d]=v.split('-');return`${d}/${m}/${y}`}
const style=document.createElement('style');style.textContent='.layout.opportunity-mode{grid-template-columns:1fr}.layout.opportunity-mode #eventCalendar{display:none!important}.layout.opportunity-mode .content{max-width:1200px;width:100%;margin:0 auto}.opp-card{border:1px solid var(--border);border-radius:13px;padding:14px;background:#fff}.opp-card h3{margin:7px 0}.opp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.opp-meta{font-size:11px;color:var(--muted);font-weight:bold;text-transform:uppercase}.opp-summary{font-size:13px;line-height:1.45}.opp-link{display:inline-block;background:var(--accent);color:#fff;text-decoration:none;border-radius:9px;padding:9px 12px;font-size:12px;font-weight:bold}.opp-deadline{font-size:12px;font-weight:bold;margin:9px 0}@media(max-width:820px){.view-tabs{overflow-x:auto}.tab-button{white-space:nowrap}.opp-grid{grid-template-columns:1fr}.news-filters{grid-template-columns:1fr 1fr}.news-filters label:last-child{grid-column:1/-1}}';document.head.appendChild(style);
const nav=document.querySelector('.view-tabs'),tab=document.createElement('button');tab.className='tab-button';tab.id='tabOportunidades';tab.type='button';tab.textContent='Oportunidades';nav.appendChild(tab);
const panel=document.createElement('section');panel.className='panel news-panel';panel.id='opportunityPanel';panel.hidden=true;panel.innerHTML='<div class="news-head"><div><h2>Oportunidades</h2><p>Trabalhe, participe, aprenda e faça parte do ecossistema do futebol feminino e da Copa do Mundo Feminina 2027.</p></div><div class="news-metrics"><div class="news-metric"><small>Abertas</small><strong id="oAbertas">0</strong></div><div class="news-metric"><small>Encerram em 7 dias</small><strong id="oUrgentes">0</strong></div><div class="news-metric"><small>Online/Híbridas</small><strong id="oOnline">0</strong></div></div></div><div class="news-filters"><label>Tipo<select id="oppCategoria"></select></label><label>Formato<select id="oppModalidade"></select></label><label>Local<select id="oppLocal"></select></label><label>Status<select id="oppStatus"></select></label><label>Busca<input id="oppBusca" placeholder="Título, organização ou tema"></label></div><div id="oppGrid" class="opp-grid"></div>';document.querySelector('#pageLayout main.content').appendChild(panel);
function fill(id,vals,label){const el=$(id),cur=el.value;el.innerHTML='<option value="">'+esc(label)+'</option>'+vals.filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR')).map(v=>'<option>'+esc(v)+'</option>').join('');if([...el.options].some(o=>o.value===cur))el.value=cur}
function filters(){fill('oppCategoria',[...new Set(O.map(x=>group(x.Categoria)))],'Todos');fill('oppModalidade',[...new Set(O.map(x=>x.Modalidade))],'Todos');fill('oppLocal',[...new Set(O.map(x=>x.CidadeUF||x.Abrangencia||x.Cidade))],'Todos');fill('oppStatus',['Inscrições abertas','Encerra em breve','Inscrições em breve','Encerrada'],'Todos');$('oppStatus').value='Inscrições abertas'}
function card(o){const s=status(o),local=o.CidadeUF||o.Abrangencia||o.Cidade||'Brasil',deadline=o.PrazoInscricao?'Inscrições até '+dateBR(o.PrazoInscricao):'Prazo não informado',link=/^https?:\/\//i.test(String(o.Link||''))?o.Link:'';return'<article class="opp-card"><div class="opp-meta">'+esc(o.Organizacao||o.Fonte||'')+'</div><div class="badges"><span class="badge">'+esc(group(o.Categoria))+'</span>'+(o.Modalidade?'<span class="badge">'+esc(o.Modalidade)+'</span>':'')+'<span class="badge">'+esc(s)+'</span></div><h3>'+esc(o.Titulo)+'</h3><p class="opp-summary">'+esc(o.Resumo||'')+'</p><div class="badges"><span class="badge">'+esc(local)+'</span>'+(o.GratuitoPago?'<span class="badge">'+esc(o.GratuitoPago)+'</span>':'')+'</div><div class="opp-deadline">'+esc(deadline)+'</div>'+(link?'<a class="opp-link" href="'+esc(link)+'" target="_blank" rel="noopener noreferrer">Ver oportunidade →</a>':'')+'</article>'}
function render(){const cat=$('oppCategoria').value,mod=$('oppModalidade').value,loc=$('oppLocal').value,st=$('oppStatus').value,q=norm($('oppBusca').value),en=O.map(o=>({...o,_s:status(o)}));const list=en.filter(o=>(!cat||group(o.Categoria)===cat)&&(!mod||o.Modalidade===mod)&&(!loc||(o.CidadeUF||o.Abrangencia||o.Cidade||'')===loc)&&(!st||(st==='Inscrições abertas'?['Inscrições abertas','Encerra em breve'].includes(o._s):o._s===st))&&(!q||norm([o.Titulo,o.Organizacao,o.Resumo,o.Categoria,o.CidadeUF,o.Abrangencia].join(' ')).includes(q))).sort((a,b)=>(a.PrazoInscricao||'9999-12-31').localeCompare(b.PrazoInscricao||'9999-12-31'));const open=en.filter(o=>['Inscrições abertas','Encerra em breve'].includes(o._s));$('oAbertas').textContent=open.length;$('oUrgentes').textContent=open.filter(o=>{const d=days(o.PrazoInscricao);return d!==null&&d>=0&&d<=7}).length;$('oOnline').textContent=open.filter(o=>/online|híbr|hybrid/i.test(o.Modalidade||'')).length;$('oppGrid').innerHTML=list.length?list.map(card).join(''):'<div class="opp-card">Nenhuma oportunidade corresponde aos filtros.</div>'}
['oppCategoria','oppModalidade','oppLocal','oppStatus'].forEach(id=>$(id).onchange=render);$('oppBusca').oninput=render;
const old=window.showView;function show(v){if(v!=='opportunities'){panel.hidden=true;$('pageLayout').classList.remove('opportunity-mode');tab.classList.remove('active');old(v);return}['eventSidebar','eventMap','eventAgenda','eventFooter'].forEach(id=>{const e=$(id);if(e)e.hidden=true});$('newsPanel').hidden=true;panel.hidden=false;$('pageLayout').classList.remove('news-mode');$('pageLayout').classList.add('opportunity-mode');$('tabEventos').classList.remove('active');$('tabNoticias').classList.remove('active');tab.classList.add('active');render()}window.showView=show;$('tabEventos').onclick=()=>show('events');$('tabNoticias').onclick=()=>show('news');tab.onclick=()=>show('opportunities');
fetch('./oportunidades.json?ts='+Date.now(),{cache:'no-store'}).then(r=>r.ok?r.json():[]).then(x=>{O=Array.isArray(x)?x:[];filters();render()}).catch(e=>{console.error('Erro ao carregar oportunidades.json',e);O=[];filters();render()});
})();